/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MembersRouteImport } from './routes/members'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AdminTournamentsIdRouteImport } from './routes/admin.tournaments.$id'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TournamentsRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsIdRoute = AdminTournamentsIdRouteImport.update({
  id: '/admin/tournaments/$id',
  path: '/admin/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/history': typeof HistoryRoute
  '/members': typeof MembersRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/auth/verify': typeof AuthVerifyRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/history': typeof HistoryRoute
  '/members': typeof MembersRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/auth/verify': typeof AuthVerifyRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/auth': typeof AuthIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/history': typeof HistoryRoute
  '/members': typeof MembersRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/auth/verify': typeof AuthVerifyRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/gallery'
    | '/hall-of-fame'
    | '/history'
    | '/members'
    | '/profile'
    | '/reset-password'
    | '/tournaments'
    | '/auth/verify'
    | '/tournaments/$id'
    | '/auth/'
    | '/admin/tournaments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/gallery'
    | '/hall-of-fame'
    | '/history'
    | '/members'
    | '/profile'
    | '/reset-password'
    | '/tournaments'
    | '/auth/verify'
    | '/tournaments/$id'
    | '/auth'
    | '/admin/tournaments/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/gallery'
    | '/hall-of-fame'
    | '/history'
    | '/members'
    | '/profile'
    | '/reset-password'
    | '/tournaments'
    | '/auth/verify'
    | '/tournaments/$id'
    | '/auth/'
    | '/admin/tournaments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  GalleryRoute: typeof GalleryRoute
  HallOfFameRoute: typeof HallOfFameRoute
  HistoryRoute: typeof HistoryRoute
  MembersRoute: typeof MembersRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TournamentsRoute: typeof TournamentsRouteWithChildren
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AdminTournamentsIdRoute: typeof AdminTournamentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments/$id': {
      id: '/admin/tournaments/$id'
      path: '/admin/tournaments/$id'
      fullPath: '/admin/tournaments/$id'
      preLoaderRoute: typeof AdminTournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TournamentsRouteChildren {
  TournamentsIdRoute: typeof TournamentsIdRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsIdRoute: TournamentsIdRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  GalleryRoute: GalleryRoute,
  HallOfFameRoute: HallOfFameRoute,
  HistoryRoute: HistoryRoute,
  MembersRoute: MembersRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TournamentsRoute: TournamentsRouteWithChildren,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
  AdminTournamentsIdRoute: AdminTournamentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
