/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BecomeOrganizerRouteImport } from './routes/become-organizer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GamesRouteImport } from './routes/games'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MusicRouteImport } from './routes/music'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OrganizersRouteImport } from './routes/organizers'
import { Route as OwnershipRouteImport } from './routes/ownership'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as FollowersIdRouteImport } from './routes/followers.$id'
import { Route as FollowingPeopleIdRouteImport } from './routes/following-people.$id'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesBlindRankingRouteImport } from './routes/games.blind-ranking'
import { Route as GamesDailyQuizRouteImport } from './routes/games.daily-quiz'
import { Route as GamesGuessClubRouteImport } from './routes/games.guess-club'
import { Route as GamesHigherLowerRouteImport } from './routes/games.higher-lower'
import { Route as GamesPenaltyRouteImport } from './routes/games.penalty'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as MembersIdRouteImport } from './routes/members.$id'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as OSlugRouteImport } from './routes/o.$slug'
import { Route as OrgFollowersIdRouteImport } from './routes/org-followers.$id'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as VoteGoatRouteImport } from './routes/vote.goat'
import { Route as AdminTournamentsIdRouteImport } from './routes/admin.tournaments.$id'
import { Route as OSlugAboutRouteImport } from './routes/o.$slug.about'
import { Route as OSlugHistoryRouteImport } from './routes/o.$slug.history'
import { Route as OSlugPostsRouteImport } from './routes/o.$slug.posts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeOrganizerRoute = BecomeOrganizerRouteImport.update({
  id: '/become-organizer',
  path: '/become-organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersRoute = OrganizersRouteImport.update({
  id: '/organizers',
  path: '/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnershipRoute = OwnershipRouteImport.update({
  id: '/ownership',
  path: '/ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowersIdRoute = FollowersIdRouteImport.update({
  id: '/followers/$id',
  path: '/followers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingPeopleIdRoute = FollowingPeopleIdRouteImport.update({
  id: '/following-people/$id',
  path: '/following-people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const GamesBlindRankingRoute = GamesBlindRankingRouteImport.update({
  id: '/blind-ranking',
  path: '/blind-ranking',
  getParentRoute: () => GamesRoute,
} as any)
const GamesDailyQuizRoute = GamesDailyQuizRouteImport.update({
  id: '/daily-quiz',
  path: '/daily-quiz',
  getParentRoute: () => GamesRoute,
} as any)
const GamesGuessClubRoute = GamesGuessClubRouteImport.update({
  id: '/guess-club',
  path: '/guess-club',
  getParentRoute: () => GamesRoute,
} as any)
const GamesHigherLowerRoute = GamesHigherLowerRouteImport.update({
  id: '/higher-lower',
  path: '/higher-lower',
  getParentRoute: () => GamesRoute,
} as any)
const GamesPenaltyRoute = GamesPenaltyRouteImport.update({
  id: '/penalty',
  path: '/penalty',
  getParentRoute: () => GamesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersRoute,
} as any)
const MembersIdRoute = MembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MembersRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const OSlugRoute = OSlugRouteImport.update({
  id: '/o/$slug',
  path: '/o/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgFollowersIdRoute = OrgFollowersIdRouteImport.update({
  id: '/org-followers/$id',
  path: '/org-followers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TournamentsRoute,
} as any)
const VoteGoatRoute = VoteGoatRouteImport.update({
  id: '/vote/goat',
  path: '/vote/goat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsIdRoute = AdminTournamentsIdRouteImport.update({
  id: '/admin/tournaments/$id',
  path: '/admin/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OSlugAboutRoute = OSlugAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => OSlugRoute,
} as any)
const OSlugHistoryRoute = OSlugHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OSlugRoute,
} as any)
const OSlugPostsRoute = OSlugPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => OSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-organizer': typeof BecomeOrganizerRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/following': typeof FollowingRoute
  '/gallery': typeof GalleryRoute
  '/games': typeof GamesRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/hall-of-fame': typeof HallOfFameRoute
  '/history': typeof HistoryRoute
  '/members': typeof MembersRouteWithChildren
  '/messages': typeof MessagesRoute
  '/music': typeof MusicRoute
  '/news': typeof NewsRouteWithChildren
  '/organizers': typeof OrganizersRoute
  '/ownership': typeof OwnershipRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/users': typeof UsersRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/followers/$id': typeof FollowersIdRoute
  '/following-people/$id': typeof FollowingPeopleIdRoute
  '/games/blind-ranking': typeof GamesBlindRankingRoute
  '/games/daily-quiz': typeof GamesDailyQuizRoute
  '/games/guess-club': typeof GamesGuessClubRoute
  '/games/higher-lower': typeof GamesHigherLowerRoute
  '/games/penalty': typeof GamesPenaltyRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/members/$id': typeof MembersIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/o/$slug': typeof OSlugRouteWithChildren
  '/org-followers/$id': typeof OrgFollowersIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/vote/goat': typeof VoteGoatRoute
  '/auth/': typeof AuthIndexRoute
  '/games/': typeof GamesIndexRoute
  '/members/': typeof MembersIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/o/$slug/about': typeof OSlugAboutRoute
  '/o/$slug/history': typeof OSlugHistoryRoute
  '/o/$slug/posts': typeof OSlugPostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-organizer': typeof BecomeOrganizerRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/following': typeof FollowingRoute
  '/gallery': typeof GalleryRoute
  '/guides': typeof GuidesRouteWithChildren
  '/hall-of-fame': typeof HallOfFameRoute
  '/history': typeof HistoryRoute
  '/messages': typeof MessagesRoute
  '/music': typeof MusicRoute
  '/news': typeof NewsRouteWithChildren
  '/organizers': typeof OrganizersRoute
  '/ownership': typeof OwnershipRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/users': typeof UsersRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/followers/$id': typeof FollowersIdRoute
  '/following-people/$id': typeof FollowingPeopleIdRoute
  '/games/blind-ranking': typeof GamesBlindRankingRoute
  '/games/daily-quiz': typeof GamesDailyQuizRoute
  '/games/guess-club': typeof GamesGuessClubRoute
  '/games/higher-lower': typeof GamesHigherLowerRoute
  '/games/penalty': typeof GamesPenaltyRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/members/$id': typeof MembersIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/o/$slug': typeof OSlugRouteWithChildren
  '/org-followers/$id': typeof OrgFollowersIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/vote/goat': typeof VoteGoatRoute
  '/auth': typeof AuthIndexRoute
  '/games': typeof GamesIndexRoute
  '/members': typeof MembersIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/o/$slug/about': typeof OSlugAboutRoute
  '/o/$slug/history': typeof OSlugHistoryRoute
  '/o/$slug/posts': typeof OSlugPostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-organizer': typeof BecomeOrganizerRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/following': typeof FollowingRoute
  '/gallery': typeof GalleryRoute
  '/games': typeof GamesRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/hall-of-fame': typeof HallOfFameRoute
  '/history': typeof HistoryRoute
  '/members': typeof MembersRouteWithChildren
  '/messages': typeof MessagesRoute
  '/music': typeof MusicRoute
  '/news': typeof NewsRouteWithChildren
  '/organizers': typeof OrganizersRoute
  '/ownership': typeof OwnershipRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/users': typeof UsersRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/followers/$id': typeof FollowersIdRoute
  '/following-people/$id': typeof FollowingPeopleIdRoute
  '/games/blind-ranking': typeof GamesBlindRankingRoute
  '/games/daily-quiz': typeof GamesDailyQuizRoute
  '/games/guess-club': typeof GamesGuessClubRoute
  '/games/higher-lower': typeof GamesHigherLowerRoute
  '/games/penalty': typeof GamesPenaltyRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/members/$id': typeof MembersIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/o/$slug': typeof OSlugRouteWithChildren
  '/org-followers/$id': typeof OrgFollowersIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/vote/goat': typeof VoteGoatRoute
  '/auth/': typeof AuthIndexRoute
  '/games/': typeof GamesIndexRoute
  '/members/': typeof MembersIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/o/$slug/about': typeof OSlugAboutRoute
  '/o/$slug/history': typeof OSlugHistoryRoute
  '/o/$slug/posts': typeof OSlugPostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-organizer'
    | '/dashboard'
    | '/feed'
    | '/following'
    | '/gallery'
    | '/games'
    | '/guides'
    | '/hall-of-fame'
    | '/history'
    | '/members'
    | '/messages'
    | '/music'
    | '/news'
    | '/organizers'
    | '/ownership'
    | '/platform'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/rules'
    | '/settings'
    | '/terms'
    | '/tournaments'
    | '/users'
    | '/api/analytics'
    | '/auth/verify'
    | '/followers/$id'
    | '/following-people/$id'
    | '/games/blind-ranking'
    | '/games/daily-quiz'
    | '/games/guess-club'
    | '/games/higher-lower'
    | '/games/penalty'
    | '/guides/$slug'
    | '/invite/$token'
    | '/members/$id'
    | '/news/$slug'
    | '/o/$slug'
    | '/org-followers/$id'
    | '/posts/$id'
    | '/tournaments/$id'
    | '/vote/goat'
    | '/auth/'
    | '/games/'
    | '/members/'
    | '/admin/tournaments/$id'
    | '/o/$slug/about'
    | '/o/$slug/history'
    | '/o/$slug/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-organizer'
    | '/dashboard'
    | '/feed'
    | '/following'
    | '/gallery'
    | '/guides'
    | '/hall-of-fame'
    | '/history'
    | '/messages'
    | '/music'
    | '/news'
    | '/organizers'
    | '/ownership'
    | '/platform'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/rules'
    | '/settings'
    | '/terms'
    | '/tournaments'
    | '/users'
    | '/api/analytics'
    | '/auth/verify'
    | '/followers/$id'
    | '/following-people/$id'
    | '/games/blind-ranking'
    | '/games/daily-quiz'
    | '/games/guess-club'
    | '/games/higher-lower'
    | '/games/penalty'
    | '/guides/$slug'
    | '/invite/$token'
    | '/members/$id'
    | '/news/$slug'
    | '/o/$slug'
    | '/org-followers/$id'
    | '/posts/$id'
    | '/tournaments/$id'
    | '/vote/goat'
    | '/auth'
    | '/games'
    | '/members'
    | '/admin/tournaments/$id'
    | '/o/$slug/about'
    | '/o/$slug/history'
    | '/o/$slug/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-organizer'
    | '/dashboard'
    | '/feed'
    | '/following'
    | '/gallery'
    | '/games'
    | '/guides'
    | '/hall-of-fame'
    | '/history'
    | '/members'
    | '/messages'
    | '/music'
    | '/news'
    | '/organizers'
    | '/ownership'
    | '/platform'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/rules'
    | '/settings'
    | '/terms'
    | '/tournaments'
    | '/users'
    | '/api/analytics'
    | '/auth/verify'
    | '/followers/$id'
    | '/following-people/$id'
    | '/games/blind-ranking'
    | '/games/daily-quiz'
    | '/games/guess-club'
    | '/games/higher-lower'
    | '/games/penalty'
    | '/guides/$slug'
    | '/invite/$token'
    | '/members/$id'
    | '/news/$slug'
    | '/o/$slug'
    | '/org-followers/$id'
    | '/posts/$id'
    | '/tournaments/$id'
    | '/vote/goat'
    | '/auth/'
    | '/games/'
    | '/members/'
    | '/admin/tournaments/$id'
    | '/o/$slug/about'
    | '/o/$slug/history'
    | '/o/$slug/posts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeOrganizerRoute: typeof BecomeOrganizerRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  FollowingRoute: typeof FollowingRoute
  GalleryRoute: typeof GalleryRoute
  GamesRoute: typeof GamesRouteWithChildren
  GuidesRoute: typeof GuidesRouteWithChildren
  HallOfFameRoute: typeof HallOfFameRoute
  HistoryRoute: typeof HistoryRoute
  MembersRoute: typeof MembersRouteWithChildren
  MessagesRoute: typeof MessagesRoute
  MusicRoute: typeof MusicRoute
  NewsRoute: typeof NewsRouteWithChildren
  OrganizersRoute: typeof OrganizersRoute
  OwnershipRoute: typeof OwnershipRoute
  PlatformRoute: typeof PlatformRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  TournamentsRoute: typeof TournamentsRouteWithChildren
  UsersRoute: typeof UsersRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  FollowersIdRoute: typeof FollowersIdRoute
  FollowingPeopleIdRoute: typeof FollowingPeopleIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OSlugRoute: typeof OSlugRouteWithChildren
  OrgFollowersIdRoute: typeof OrgFollowersIdRoute
  PostsIdRoute: typeof PostsIdRoute
  VoteGoatRoute: typeof VoteGoatRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AdminTournamentsIdRoute: typeof AdminTournamentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-organizer': {
      id: '/become-organizer'
      path: '/become-organizer'
      fullPath: '/become-organizer'
      preLoaderRoute: typeof BecomeOrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers': {
      id: '/organizers'
      path: '/organizers'
      fullPath: '/organizers'
      preLoaderRoute: typeof OrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ownership': {
      id: '/ownership'
      path: '/ownership'
      fullPath: '/ownership'
      preLoaderRoute: typeof OwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followers/$id': {
      id: '/followers/$id'
      path: '/followers/$id'
      fullPath: '/followers/$id'
      preLoaderRoute: typeof FollowersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following-people/$id': {
      id: '/following-people/$id'
      path: '/following-people/$id'
      fullPath: '/following-people/$id'
      preLoaderRoute: typeof FollowingPeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/blind-ranking': {
      id: '/games/blind-ranking'
      path: '/blind-ranking'
      fullPath: '/games/blind-ranking'
      preLoaderRoute: typeof GamesBlindRankingRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/daily-quiz': {
      id: '/games/daily-quiz'
      path: '/daily-quiz'
      fullPath: '/games/daily-quiz'
      preLoaderRoute: typeof GamesDailyQuizRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/guess-club': {
      id: '/games/guess-club'
      path: '/guess-club'
      fullPath: '/games/guess-club'
      preLoaderRoute: typeof GamesGuessClubRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/higher-lower': {
      id: '/games/higher-lower'
      path: '/higher-lower'
      fullPath: '/games/higher-lower'
      preLoaderRoute: typeof GamesHigherLowerRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/penalty': {
      id: '/games/penalty'
      path: '/penalty'
      fullPath: '/games/penalty'
      preLoaderRoute: typeof GamesPenaltyRouteImport
      parentRoute: typeof GamesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/o/$slug': {
      id: '/o/$slug'
      path: '/o/$slug'
      fullPath: '/o/$slug'
      preLoaderRoute: typeof OSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-followers/$id': {
      id: '/org-followers/$id'
      path: '/org-followers/$id'
      fullPath: '/org-followers/$id'
      preLoaderRoute: typeof OrgFollowersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/vote/goat': {
      id: '/vote/goat'
      path: '/vote/goat'
      fullPath: '/vote/goat'
      preLoaderRoute: typeof VoteGoatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments/$id': {
      id: '/admin/tournaments/$id'
      path: '/admin/tournaments/$id'
      fullPath: '/admin/tournaments/$id'
      preLoaderRoute: typeof AdminTournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$slug/about': {
      id: '/o/$slug/about'
      path: '/about'
      fullPath: '/o/$slug/about'
      preLoaderRoute: typeof OSlugAboutRouteImport
      parentRoute: typeof OSlugRoute
    }
    '/o/$slug/history': {
      id: '/o/$slug/history'
      path: '/history'
      fullPath: '/o/$slug/history'
      preLoaderRoute: typeof OSlugHistoryRouteImport
      parentRoute: typeof OSlugRoute
    }
    '/o/$slug/posts': {
      id: '/o/$slug/posts'
      path: '/posts'
      fullPath: '/o/$slug/posts'
      preLoaderRoute: typeof OSlugPostsRouteImport
      parentRoute: typeof OSlugRoute
    }
  }
}

interface GamesRouteChildren {
  GamesBlindRankingRoute: typeof GamesBlindRankingRoute
  GamesDailyQuizRoute: typeof GamesDailyQuizRoute
  GamesGuessClubRoute: typeof GamesGuessClubRoute
  GamesHigherLowerRoute: typeof GamesHigherLowerRoute
  GamesPenaltyRoute: typeof GamesPenaltyRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesBlindRankingRoute: GamesBlindRankingRoute,
  GamesDailyQuizRoute: GamesDailyQuizRoute,
  GamesGuessClubRoute: GamesGuessClubRoute,
  GamesHigherLowerRoute: GamesHigherLowerRoute,
  GamesPenaltyRoute: GamesPenaltyRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface MembersRouteChildren {
  MembersIdRoute: typeof MembersIdRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersIdRoute: MembersIdRoute,
  MembersIndexRoute: MembersIndexRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface TournamentsRouteChildren {
  TournamentsIdRoute: typeof TournamentsIdRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsIdRoute: TournamentsIdRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

interface OSlugRouteChildren {
  OSlugAboutRoute: typeof OSlugAboutRoute
  OSlugHistoryRoute: typeof OSlugHistoryRoute
  OSlugPostsRoute: typeof OSlugPostsRoute
}

const OSlugRouteChildren: OSlugRouteChildren = {
  OSlugAboutRoute: OSlugAboutRoute,
  OSlugHistoryRoute: OSlugHistoryRoute,
  OSlugPostsRoute: OSlugPostsRoute,
}

const OSlugRouteWithChildren = OSlugRoute._addFileChildren(OSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeOrganizerRoute: BecomeOrganizerRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  FollowingRoute: FollowingRoute,
  GalleryRoute: GalleryRoute,
  GamesRoute: GamesRouteWithChildren,
  GuidesRoute: GuidesRouteWithChildren,
  HallOfFameRoute: HallOfFameRoute,
  HistoryRoute: HistoryRoute,
  MembersRoute: MembersRouteWithChildren,
  MessagesRoute: MessagesRoute,
  MusicRoute: MusicRoute,
  NewsRoute: NewsRouteWithChildren,
  OrganizersRoute: OrganizersRoute,
  OwnershipRoute: OwnershipRoute,
  PlatformRoute: PlatformRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  TournamentsRoute: TournamentsRouteWithChildren,
  UsersRoute: UsersRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  FollowersIdRoute: FollowersIdRoute,
  FollowingPeopleIdRoute: FollowingPeopleIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  OSlugRoute: OSlugRouteWithChildren,
  OrgFollowersIdRoute: OrgFollowersIdRoute,
  PostsIdRoute: PostsIdRoute,
  VoteGoatRoute: VoteGoatRoute,
  AuthIndexRoute: AuthIndexRoute,
  AdminTournamentsIdRoute: AdminTournamentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
